### ISSUE TITLE
[QUESTION/BUG?] Problem with getting started guide

### ISSUE THREAD

**Issue by Emmeral** [jahstreet/spark-on-kubernetes-helm#77]
I tried to follow the getting started guide in the README.md. But if I submit a batch job to Livy it ends up in the state `dead`. However, I can see in my cluster that the spark driver and executor pods are deployed. Also, according to their logs, they seem to perform all calculations successfully.

If I look at the logs of the livy pod, I get the following error:

```
22/03/22 15:01:16 ERROR SparkKubernetesApp: Couldn't refresh Kubernetes state
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc.cluster.local/apis/extensions/v1beta1/namespaces/livy/ingresses?labelSelector=spark-app-tag%3Dlivy-batch-4-HtbACzka. Message: 404 page not found
.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:589)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:528)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:492)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:433)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:166)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:640)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:79)
        at org.apache.livy.utils.LivyKubernetesClient.getIngress(SparkKubernetesApp.scala:503)
        at org.apache.livy.utils.LivyKubernetesClient.getApplicationReport(SparkKubernetesApp.scala:487)
        at org.apache.livy.utils.SparkKubernetesApp$$anonfun$1$$anonfun$4.apply(SparkKubernetesApp.scala:189)
        at org.apache.livy.utils.SparkKubernetesApp$$anonfun$1$$anonfun$4.apply(SparkKubernetesApp.scala:189)
        at scala.util.Try$.apply(Try.scala:192)
        at org.apache.livy.utils.SparkKubernetesApp$.org$apache$livy$utils$SparkKubernetesApp$$withRetry(SparkKubernetesApp.scala:104)
        at org.apache.livy.utils.SparkKubernetesApp$$anonfun$1.apply$mcV$sp(SparkKubernetesApp.scala:189)
        at org.apache.livy.Utils$$anon$1.run(Utils.scala:97)
```

It seems like livy can't refresh the state of the spark pods because it is missing an ingress. Any idea how to fix this or what the actual problem is?

**Comment by aegisx0828** [comment]
Hello, I'm also using the project well,
What happens to the k8s environment version?

I am also experiencing the same issue.
Roughly checking, after k8s version 1.22, v1beta1 of k8s ingress api has been deprecated.

I wonder if there is any action going on for k8s 1.22 .

![스크린샷 2022-06-08 오전 11 09 40](https://user-images.githubusercontent.com/7587602/172516202-a5698ab3-f572-416f-a3a8-574f26b2f0a7.png)

**Comment by imperio-wxm** [comment]
Is there any progress? k8s version 1.22+, this api has been deprecated.

**Comment by jahstreet** [comment]
Closing this issue in favour of https://github.com/JahstreetOrg/spark-on-kubernetes-helm/issues/82 within which it will be resolved, lets continue there.

And thanks for the patience 🙏 .
